kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: impvc
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: impvc
